# Generated by Django 2.0.6 on 2019-12-20 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='ForeignKey',
        ),
        migrations.AlterField(
            model_name='userimages',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
    ]
