# Generated by Django 2.0.6 on 2020-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylistprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='alluser',
            name='BusinessName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='alluser',
            name='TypeofStylist',
            field=models.CharField(default='Cosmetologist', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alluser',
            name='is_stylist',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='StylistProfile',
        ),
    ]
