# Generated by Django 2.0.6 on 2019-12-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0002_auto_20191220_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_stylist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
