# Generated by Django 2.0.6 on 2020-01-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0003_remove_alluser_is_stylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=11, null=True),
        ),
    ]
