# Generated by Django 2.0.6 on 2019-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0003_auto_20191223_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='TypeofStylist',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8),
        ),
    ]
