# Generated by Django 2.0.6 on 2020-01-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0004_auto_20200113_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluser',
            old_name='AccountType',
            new_name='Account_Type',
        ),
    ]
