# Generated by Django 2.0.6 on 2020-01-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0005_auto_20200114_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluser',
            old_name='Account_Type',
            new_name='AccountType',
        ),
    ]
