# Generated by Django 2.0.6 on 2019-12-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0005_auto_20191226_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_user',
            new_name='user',
        ),
    ]
