# Generated by Django 2.0.6 on 2019-12-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0006_auto_20191226_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_stylist',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_user',
            field=models.NullBooleanField(default=True),
        ),
    ]
