# Generated by Django 2.0.6 on 2019-12-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0007_auto_20191227_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DateOfBirth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_Picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='TypeofStylist',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
