# Generated by Django 2.0.6 on 2019-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0008_auto_20191227_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, null=True),
        ),
    ]
