# Generated by Django 2.0.6 on 2019-12-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0009_auto_20191227_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
