# Generated by Django 2.0.6 on 2019-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0011_auto_20191227_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='TypeofStylist',
            field=models.CharField(default='Cosmetologist', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
