# Generated by Django 2.0.6 on 2019-12-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0012_auto_20191231_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
