# Generated by Django 2.0.6 on 2020-01-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0013_auto_20191231_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, null=True),
        ),
    ]
