# Generated by Django 2.0.6 on 2020-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0014_auto_20200101_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_stylist',
            field=models.BooleanField(default=False),
        ),
    ]
