# Generated by Django 2.0.6 on 2020-01-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0015_auto_20200102_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=35.148272, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=-90.1108723, max_digits=10, null=True),
        ),
    ]
