# Generated by Django 2.0.6 on 2020-01-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimpApp', '0016_auto_20200102_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
